export const states = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttarakhand",
  "Uttar Pradesh",
  "West Bengal",
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli & Daman and Diu",
  "Delhi",
  "Lakshadweep",
  "Puducherry",
];

export const stateCodes = {
  AD: "37",
  AR: "12",
  AS: "18",
  BR: "10",
  CG: "22",
  DL: "07",
  GA: "30",
  GJ: "24",
  HR: "06",
  HP: "02",
  JK: "01",
  JH: "20",
  KA: "29",
  KL: "32",
  LD: "31",
  MP: "23",
  MH: "27",
  MN: "14",
  ML: "17",
  MZ: "15",
  NL: "13",
  OD: "21",
  PY: "34",
  PB: "03",
  RJ: "08",
  SK: "11",
  TN: "33",
  TS: "36",
  TR: "16",
  UP: "09",
  UK: "05",
  WB: "19",
  AN: "35",
  CH: "04",
  DNHDD: "26",
  LA: "38",
  OT: "97",
};

export const placeOfSupply = {
  "Andhra Pradesh": "AD",
  "Arunachal Pradesh": "AR",
  Assam: "AS",
  Bihar: "BR",
  Chhattisgarh: "CG",
  Goa: "GA",
  Gujarat: "GJ",
  Haryana: "HR",
  "Himachal Pradesh": "HP",
  "Jammu and Kashmir": "JK",
  Jharkhand: "JH",
  Karnataka: "KA",
  Kerala: "KL",
  "Madhya Pradesh": "MP",
  Maharashtra: "MH",
  Manipur: "MN",
  Meghalaya: "ML",
  Mizoram: "MZ",
  Nagaland: "NL",
  Odisha: "OD",
  Punjab: "PB",
  Rajasthan: "RJ",
  Sikkim: "SK",
  "Tamil Nadu": "TN",
  Telangana: "TS",
  Tripura: "TR",
  Uttarakhand: "UK",
  "Uttar Pradesh": "UP",
  "West Bengal": "WB",
  "Andaman and Nicobar Islands": "AN",
  Chandigarh: "CH",
  "Dadra and Nagar Haveli & Daman and Diu": "DNHDD",
  Delhi: "DL",
  Lakshadweep: "LD",
  Puducherry: "PY",
};
